### ISSUE TITLE
"Washed" Colors

### ISSUE THREAD

**Issue by brunoaugusto** [fnordware/AdobeWebM#42]
I'm not exactly sure if this is an issue or if it's an expected behavior of the WebM standards but, in any case, I believe it's worth to mention.

Although I'm not an experienced video editor I noticed something I can describe, for the lack of better word, "washed" colors after converting some random videos on my PC (Windows) before I could throw away all the originals and save a huge disk space.

Allow me to illustrate the case with one of my favorite TV Shows: My Wife and Kids. :smile: 

[This](http://i.imgur.com/63j5845.png) is a screenshot taken with VLC from the original video which the person alleged it came straight from the Blu-ray (I doubt, but I can't confirm) although after encoded with Adobe Premiere CC 2017 using the basic HD 720p preset from H.264 group. No effects applied at all.

[This one](http://i.imgur.com/H7Vm6Zr.png) is another screenshot, also taken with VLC, more or less at same point of the previous one, using the VP8 Codec, VBR Method with only 1-Pass and 1 Mbps of bitrate.

They look more clear, yes, but different, kind of "washed".

In this particular scene it doesn't look too bad because the actor(s) is/are in a dark bedroom. The color issue becomes more noticeable when there are more or wider light source(s), like in a living room, i.e. [Original](http://i.imgur.com/6ByLHrx.png) and [WebM](http://i.imgur.com/1WbwMsV.png).

I thought I could treat the case like an image and applied Levels and (Lumetri) Curves with values similar to Photoshop's Midtone Darkers Preset and Linear Contrast (respectively) and I've got [this](http://i.imgur.com/369PlBP.png).

A bit too dark, specially around the scene (Curves' fault >.<) but it's also a working progress. I just add here as background information to describe a (possible) workaround to the color issue, assuming there is indeed a color issue.

Last but not least, thank you for the amazing job

**Comment by fnordware** [comment]
Yeah, I can certainly see a difference. The latter looks more yellow/green, while the former looks more red/magenta.

I guess you're importing the original into Premiere or Media Encoder to create the WebM? What does it look like in that program? What if you export a PNG sequence?

If I had to guess, it has something with the different YUV primaries between 601 and 709.

**Comment by brunoaugusto** [comment]
Curiously, Premiere's preview shows me pretty much what I get from the WebM screenshot, that's why I captured after rendered instead.

I read somewhere in a possibly dead FFMPEG forum, in which a user was trying to convert a video to WebmM with it and had the same color issue I described and someone commented:

> It is expected to see some changes after converting rgb24 to yuv420p

Not sure if that's apply to the case but it could be useful, who knows

**Comment by fnordware** [comment]
OK, I've done some more digging and I think I can say with 100% certainty that my hunch was correct: the issue here is that the two programs are using different YUV coefficients. In this case it appears Premiere is using 709 while VLC is using 601. If the original source is Blu-ray, then it should have been in 709, so Premiere is showing it correctly, not VLC.

Ideally these programs would let you choose which coefficients to use. Since Premiere doesn't, I've made a couple LUT files you can apply in Premiere to convert to the other coefficients. Get them here:

http://www.fnordware.com/downloads/701to609_LUTs.zip

This change is not due to RGB<->YUV conversion. 4:4:4 RGB to 4:2:0 YUV is not lossless, but it gives you various other artifacts, not big color shifts.
